name: Deploy Production code in EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies and build React app
      run: |
        npm i || { echo "npm ci failed, trying npm install"; npm install; }
        npm run build || { echo "Build failed"; exit 1; }

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy build files to EC2
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ ubuntu@54.219.112.181:/var/www/react-production || { echo "File copy failed"; exit 1; }

    - name: Restart Nginx on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.219.112.181 << 'EOF'
          sudo systemctl restart nginx || { echo "Failed to restart Nginx"; exit 1; }
          echo "React frontend deployment completed successfully"
        EOF
