name: Deploy Production code in EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies and build React app
      run: |
        npm i || { echo "npm ci failed, trying npm install"; npm install; }
        npm run build || { echo "Build failed"; exit 1; }

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy build files to EC2
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ ubuntu@54.219.112.181:/home/ubuntu/temp-react-build || { echo "File copy failed"; exit 1; }

    - name: Move build files to web directory with sudo
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.219.112.181 << 'EOF'
          sudo rm -rf /var/www/react-production/*
          sudo mv /home/ubuntu/temp-react-build/* /var/www/react-production/
          sudo chown -R www-data:www-data /var/www/react-production
          sudo chmod -R 755 /var/www/react-production
          echo "Files moved successfully"
        EOF
